In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

# IMPORTANT: To find the correct path for your 'train.txt' file in Google Drive:
# 1. In the left sidebar of Colab, click the 'Files' icon (folder icon).
# 2. Expand 'drive' -> 'MyDrive'.
# 3. Navigate through your folders until you find 'train.txt'.
# 4. Right-click on 'train.txt' and select 'Copy path'.
# 5. Paste that copied path below, replacing the placeholder.

data_path = '/content/drive/MyDrive/train.txt' # <-- I've updated this to use train.txt

try:
    # pandas.read_csv can often handle tab-separated or space-separated text files too.
    # If your file is not comma-separated, you might need to specify the separator, e.g., sep='\t' for tab-separated.
    df = pd.read_csv(data_path)
    print(f"Successfully loaded dataset from: {data_path}")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{data_path}' was not found. Please double-check the path using the Colab file browser.")
except Exception as e:
    print(f"An error occurred while loading the dataset: {e}. Check if the file format is compatible with pd.read_csv or if you need to specify a 'sep' argument.")

Successfully loaded dataset from: /content/drive/MyDrive/train.txt

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
df.shape

(1460, 81)

In [ ]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [ ]:
df[["GrLivArea", "BedroomAbvGr", "FullBath", "SalePrice"]].head()

   GrLivArea  BedroomAbvGr  FullBath  SalePrice
0       1710             3         2     208500
1       1262             3         2     181500
2       1786             3         2     223500
3       1717             3         1     140000
4       2198             4         2     250000

In [ ]:
df[["GrLivArea", "BedroomAbvGr", "FullBath", "SalePrice"]].isnull().sum()

GrLivArea       0
BedroomAbvGr    0
FullBath        0
SalePrice       0
dtype: int64

In [ ]:
df[["GrLivArea", "BedroomAbvGr", "FullBath", "SalePrice"]].dtypes

GrLivArea       int64
BedroomAbvGr    int64
FullBath        int64
SalePrice       int64
dtype: object

In [ ]:
df[["GrLivArea", "BedroomAbvGr", "FullBath", "SalePrice"]].describe()

         GrLivArea  BedroomAbvGr     FullBath      SalePrice
count  1460.000000   1460.000000  1460.000000    1460.000000
mean   1515.463699      2.866438     1.565068  180921.195890
std     525.480383      0.815778     0.550916   79442.502883
min     334.000000      0.000000     0.000000   34900.000000
25%    1129.500000      2.000000     1.000000  129975.000000
50%    1464.000000      3.000000     2.000000  163000.000000
75%    1776.750000      3.000000     2.000000  214000.000000
max    5642.000000      8.000000     3.000000  755000.000000

In [ ]:
house_df = df[["GrLivArea", "BedroomAbvGr", "FullBath", "SalePrice"]]

house_df = house_df.rename(columns={
    "GrLivArea": "square_footage",
    "BedroomAbvGr": "bedrooms",
    "FullBath": "bathrooms",
    "SalePrice": "price"
})

house_df.head()

   square_footage  bedrooms  bathrooms   price
0            1710         3          2  208500
1            1262         3          2  181500
2            1786         3          2  223500
3            1717         3          1  140000
4            2198         4          2  250000

In [ ]:
house_df.to_csv("clean_house_price_dataset.csv", index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [ ]:
df.head()
df.shape
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

## 1. Import Libraries

This section imports all the necessary libraries for data manipulation, model training, evaluation, and saving.

In [ ]:
#path
data_path = '/content/drive/MyDrive/train.txt'

print("Dataset loaded successfully!")
df.head()

Dataset loaded successfully!

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## 2. Load and Prepare Data

Here, we load the dataset from Google Drive and select the features (independent variables) and the target variable (dependent variable) for our model. We also rename columns for clarity.

In [ ]:
house_df = df[["GrLivArea", "BedroomAbvGr", "FullBath", "SalePrice"]]

house_df = house_df.rename(columns={
    "GrLivArea": "square_footage",
    "BedroomAbvGr": "bedrooms",
    "FullBath": "bathrooms",
    "SalePrice": "price"
})

house_df.head()

   square_footage  bedrooms  bathrooms   price
0            1710         3          2  208500
1            1262         3          2  181500
2            1786         3          2  223500
3            1717         3          1  140000
4            2198         4          2  250000

## 3. Define Features (X) and Target (y)

We separate our dataset into features (`X`), which are the inputs to our model, and the target (`y`), which is what we want to predict.

In [ ]:
# Select relevant features and the target variable for house price prediction.
house_df = df[["GrLivArea", "BedroomAbvGr", "FullBath", "SalePrice"]]

# Rename columns to more intuitive names for better readability.
house_df = house_df.rename(columns={
    "GrLivArea": "square_footage",
    "BedroomAbvGr": "bedrooms",
    "FullBath": "bathrooms",
    "SalePrice": "price"
})

# Display the first few rows of the prepared DataFrame.
house_df.head()

In [ ]:
X = house_df[["square_footage", "bedrooms", "bathrooms"]]

y = house_df["price"]

## 4. Split Data into Training and Testing Sets

To evaluate our model's performance on unseen data, we split the dataset into training and testing sets. The model learns from the training data and is then evaluated on the testing data.

In [ ]:
# X contains the independent variables (features) used to predict the house price.
X = house_df[["square_footage", "bedrooms", "bathrooms"]]

# y contains the dependent variable (target), which is the house price.
y = house_df["price"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (1168, 3)
Testing data: (292, 3)

## 5. Model Training

Here, we initialize a Linear Regression model and train it using our training data (`X_train` and `y_train`). The model learns the relationship between the features and the target variable.

In [ ]:
# Split the data: 80% for training and 20% for testing.
# random_state ensures reproducibility of the split.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data shape:", X_train.shape, y_train.shape)
print("Testing data shape:", X_test.shape, y_test.shape)

In [ ]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

## 6. Make Predictions

After training, we use the model to make predictions on the unseen test data (`X_test`).

In [ ]:
# Initialize the Linear Regression model.
model = LinearRegression()

# Train the model using the training data.
model.fit(X_train, y_train)

print("Linear Regression Model trained successfully!")

In [ ]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[113410.67255298 305081.87775899 135904.78562983 205424.67564124
 227502.68349004 121157.48079629 205577.98056584 183787.20378269
 121157.48079629 147219.22233196]

## 7. Model Evaluation

We evaluate the model's performance using common regression metrics: Mean Absolute Error (MAE), Mean Squared Error (MSE), and R-squared (R2) score. These metrics help us understand how well our model is predicting house prices.

In [ ]:
# Use the trained model to predict house prices on the test set.
y_pred = model.predict(X_test)

print("First 10 predicted house prices:")
print(y_pred[:10])

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Absolute Error: 35788.061292436294
Mean Squared Error: 2806426667.247853
R2 Score: 0.6341189942328371

## 8. Make a New Prediction

Here, we demonstrate how to use the trained model to predict the price of a hypothetical new house with specified square footage, bedrooms, and bathrooms.

In [ ]:
# Calculate Mean Absolute Error (MAE): Average absolute difference between actual and predicted values.
mae = mean_absolute_error(y_test, y_pred)
# Calculate Mean Squared Error (MSE): Average of the squared differences, penalizes larger errors.
mse = mean_squared_error(y_test, y_pred)
# Calculate R2 Score: Proportion of the variance in the dependent variable predictable from the independent variables.
r2 = r2_score(y_test, y_pred)

print("Model Evaluation Metrics:")
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R2 Score:", r2)

In [ ]:
new_house = [[2000, 3, 2]]

predicted_price = model.predict(new_house)

print("Predicted House Price:", predicted_price[0])

Predicted House Price: 240377.51479736282

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

## 9. Save the Trained Model

Finally, we save the trained machine learning model to a file using `joblib`. This allows us to reuse the model later without retraining it.

In [ ]:
# Define a hypothetical new house with specific features: square footage, bedrooms, and bathrooms.
new_house = [[2000, 3, 2]] # Example: 2000 sq ft, 3 bedrooms, 2 bathrooms

# Predict the price of this new house using the trained model.
predicted_price = model.predict(new_house)

print("Predicted Price for the new house:", predicted_price[0])

In [ ]:
joblib.dump(model, "house_price_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [ ]:
# Save the trained Linear Regression model to a file named 'house_price_model.pkl'.
joblib.dump(model, "house_price_model.pkl")

print("Model saved successfully as 'house_price_model.pkl'!")